### ISSUE TITLE
Log to file feature?

### ISSUE THREAD

**Issue by Maxwell3e8** [Intelix8996/SPlotter#1]
I looked for a long time to find a program that works well with floating point numbers and can also run on an old Windows XP computer that I use for data monitoring. Among almost a dozen programs, this is the only one I found and it works quite well. Thanks for writing it!

I would suggest adding some log to file feature for the numbers and perhaps saving the plot to an image.

Another nice feature would be to keep the width of the plot fixed, so after a specified number of points the old data roll off the screen automatically.

**Comment by Intelix8996** [comment]
Hi, thank you for using my app! Unfortunately, this repository is obsolete and will no longer be updated.
